const constants = {
    ABOUT: "About",
    AWSICON: "Amazon Web Services Icon",
    CAPTCHA: "Captcha",
    CHECKMARKICON: "Checkmark Icon",
    CLICKHERE: "Click Here",
    CONTACT: "Contact",
    CONTACTCTS: "Contact CTS",
    CONTACTFORM: "Contact Form",
    CORREGIDOR: "Corregidor",
    CORREGIDORLOGOVIDEO: "Corregidor Logo Video Background",
    CORREGIDORTECHNOLOGYSERVICES: "Corregidor Technology Services",
    CORREGIDORTECHNOLOGYSERVICESLOGO: "Corregidor Technology Services Logo", 
    DOCKERICON: "Docker Icon",
    EMAIL: "Email: ",
    ENVELOPEICON: "Envelope Icon",
    HOME: "Home",
    INSTAGRAMLINKTEXT: "Link to Corregidor Tech on Instagram",
    INSTAGRAMURL: "https://www.instagram.com/corregidortech/", 
    JAVASCRIPTICON: "JavaScript Icon",    
    LEARNMORE: "Learn More", 
    LIGHTNINGBOLTICON: "Lightning Bolt Icon",
    MESSAGE: "Message: ",
    MESSAGESENT: "Message Sent!",
    MICROSOFTICON: "Microsoft Icon",
    NAME: "Name: ",
    NODEICON: "Node.js Icon", 
    OUREXPERIENCE: "Our Experience", 
    PLEASECOMPLETECAPTCHA: "Please Complete Captcha!",
    PLEASEPROVIDEVALIDEMAIL: "Please provide a valid email address!",
    REACTICON: "ReactJS Icon",
    SENDEMAILAPIURL: "https://corregidorapi.azurewebsites.net/api/email/SendEmail",
    SENDING: "Sending...",
    SERVICES: "Services",
    SUBMIT: "Submit",
    TECHNOLOGIES: "Technologies",
    TECHNOLOGYSERVICES: "Technology Services",
    TWITTERLINKTEXT: "Link to Corregidor Tech on Twitter",
    TWITTERURL: "https://twitter.com/corregidortech",
    VALUESSTATEMENTLONG: "Corregidor Technology Services provides system engineering consulting services",
    VALUESTATEMENTSHORT: "CTS provides system engineering consulting services",
    WHATWEDO: "What We Do"
};

export default constants; 